# Generated by Django 5.1.1 on 2024-11-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAlfabetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=2, null=True)),
                ('indice', models.IntegerField()),
                ('retroalimentacion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaAlfabeticaSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=2, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.IntegerField()),
                ('tipoNota', models.CharField(choices=[('Practica', 'Practica'), ('Parcial', 'Parcial'), ('Final', 'Final'), ('Unica', 'Unica')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaNumerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDeNota', models.CharField(choices=[('Practica', 'Practica'), ('Parcial', 'Parcial'), ('Final', 'Final'), ('Unica', 'Unica')], max_length=20)),
                ('indice', models.IntegerField()),
                ('valor', models.FloatField(default=-1)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotaXCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaFinal', models.CharField(max_length=2, null=True)),
                ('retroalimentacionFinal', models.TextField(null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('clave', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('nivelInicial', models.CharField(blank=True, max_length=255)),
                ('nivelEnProceso', models.CharField(blank=True, max_length=255)),
                ('nivelSatisfactorio', models.CharField(blank=True, max_length=255)),
                ('nivelSobresaliente', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetenciaXHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadEvaluaciones', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('idCompetencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificacion.competencia')),
            ],
        ),
    ]
