# Generated by Django 5.1.1 on 2024-11-16 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
        ('matricula', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alumnoxhorario',
            unique_together={('alumno', 'horario', 'periodo')},
        ),
    ]
