# Generated by Django 5.1.1 on 2024-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_alumnoxhorario_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionmatricula',
            name='estadoMatricula',
            field=models.CharField(choices=[('Prematricula', 'Prematricula'), ('Matricula', 'Matricula'), ('Publicacion Cursos', 'Publicacion Cursos'), ('Matricula Extemporanea', 'Matricula Extemporanea'), ('Publicación Mat. Ext', 'Publicación Mat. Ext'), ('Ciclo Lectivo', 'Ciclo Lectivo'), ('Fin de Ciclo', 'Fin de Ciclo')], default='Ciclo Lectivo', max_length=30),
        ),
    ]
