# Generated by Django 5.1.1 on 2024-11-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0003_alter_informacionmatricula_estadomatricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='extemporanea',
        ),
        migrations.AddField(
            model_name='lineainscripcion',
            name='extemporanea',
            field=models.BooleanField(default=False),
        ),
    ]
