# Generated by Django 5.1.1 on 2024-11-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0005_alter_informacionmatricula_estadomatricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaAlumnoXHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumnoxhorario', models.BigIntegerField()),
                ('vez', models.IntegerField()),
                ('promedioPcs', models.FloatField()),
                ('promedioFinal', models.FloatField()),
                ('retirado', models.BooleanField()),
                ('alumnoxhorario_activo', models.BooleanField()),
                ('id_alumno', models.BigIntegerField()),
                ('alumno_nombre', models.CharField(max_length=100)),
                ('alumno_primerApellido', models.CharField(max_length=100)),
                ('alumno_segundoApellido', models.CharField(max_length=100)),
                ('codigo_alumno', models.CharField(max_length=28)),
                ('id_horario', models.BigIntegerField()),
                ('claveHorario', models.CharField(max_length=5)),
                ('numVacantes', models.IntegerField()),
                ('numMatriculados', models.IntegerField()),
                ('numAprobados', models.IntegerField()),
                ('numDesaprobados', models.IntegerField()),
                ('id_curso', models.BigIntegerField()),
                ('curso_clave', models.CharField(max_length=50)),
                ('curso_nombre', models.CharField(max_length=100)),
                ('curso_creditos', models.FloatField()),
                ('id_periodo', models.BigIntegerField()),
                ('periodo_academico', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('id_inscripcion', models.BigIntegerField()),
                ('inscripcion_creditos', models.FloatField()),
                ('inscripcion_activa', models.BooleanField()),
            ],
            options={
                'db_table': 'vista_alumnoxhorario_completa',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='informacionmatricula',
            name='estadoMatricula',
            field=models.CharField(choices=[('Prematricula', 'Prematricula'), ('Matricula', 'Matricula'), ('Publicacion Matricula', 'Publicacion Matricula'), ('Matricula Extemporanea', 'Matricula Extemporanea'), ('Publicación Mat. Ext', 'Publicación Mat. Ext'), ('Ciclo Lectivo', 'Ciclo Lectivo'), ('Fin de Ciclo', 'Fin de Ciclo'), ('Tiempo Muerto', 'Tiempo Muerto')], default='Ciclo Lectivo', max_length=30),
        ),
    ]
