# Generated by Django 5.1.1 on 2024-12-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0007_alter_alumnoxhorario_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnoxhorario',
            options={'managed': True},
        ),
    ]
