# Generated by Django 5.1.1 on 2024-11-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('matricula', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='alumnos',
            field=models.ManyToManyField(blank=True, related_name='horarios', through='matricula.AlumnoXHorario', to='usuarios.alumno'),
        ),
        migrations.AddField(
            model_name='horario',
            name='idCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='idprofesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.profesor'),
        ),
        migrations.CreateModel(
            name='RequisitoCreditos',
            fields=[
                ('requisitobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cursos.requisitobase')),
                ('total_creditos', models.FloatField()),
            ],
            bases=('cursos.requisitobase',),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.requisitobase'),
        ),
        migrations.CreateModel(
            name='RequisitoCursos',
            fields=[
                ('requisitobase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cursos.requisitobase')),
                ('cursos', models.ManyToManyField(related_name='requisito_para_cursos', to='cursos.curso')),
            ],
            bases=('cursos.requisitobase',),
        ),
    ]
