# Generated by Django 5.1.1 on 2024-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='numInscritos',
            field=models.IntegerField(default=0),
        ),
    ]
