# Generated by Django 5.1.1 on 2024-11-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionMatricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacionDeCursos', models.DateField(default='2000-01-01')),
                ('inicioPreMatricula', models.DateField(default='2000-01-01')),
                ('cierrePreMatricula', models.DateField(default='2000-01-01')),
                ('publicacionCursosMatInicio', models.DateField(default='2000-01-01')),
                ('publicacionCursosMatFin', models.DateField(default='2000-01-01')),
                ('inicioMatExtemporanea', models.DateField(default='2000-01-01')),
                ('finMatExtemporanea', models.DateField(default='2000-01-01')),
                ('publicacionMatExtemporanea', models.DateField(default='2000-01-01')),
                ('fin', models.DateField(default='2000-01-01')),
                ('estadoMatricula', models.CharField(choices=[('Prematricula', 'Prematricula'), ('Publicacion Cursos', 'Publicacion Cursos'), ('Matricula Extemporanea', 'Matricula Extemporanea'), ('Publicación Mat. Ext', 'Publicación Mat. Ext'), ('Ciclo Lectivo', 'Ciclo Lectivo'), ('Fin de Ciclo', 'Fin de Ciclo')], default='Ciclo Lectivo', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoXHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vez', models.IntegerField()),
                ('promedioPcs', models.FloatField(default=-1)),
                ('promedioFinal', models.FloatField(default=-1)),
                ('retirado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoXhorarios', to='usuarios.alumno')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoXhorarios', to='cursos.horario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoXhorarios', to='cursos.periodoacademico')),
            ],
            options={
                'unique_together': {('alumno', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='AlumnoRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(null=True)),
                ('estadoSolicitud', models.BooleanField(default=True)),
                ('estadoRetiro', models.BooleanField(default=False)),
                ('idAlumnoXHorario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiroHorarios', to='matricula.alumnoxhorario')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCreditos', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('extemporanea', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion', to='usuarios.alumno')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='LineaInscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicionRelativa', models.IntegerField()),
                ('seleccionado', models.BooleanField(default=False)),
                ('permitido', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineasDeInscripcion', to='cursos.horario')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineasDeInscripcion', to='matricula.inscripcion')),
            ],
        ),
    ]
