# Generated by Django 5.1.1 on 2024-12-13 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0006_vistaalumnoxhorario_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumnoxhorario',
            table='matricula_alumnoxhorario',
        ),
    ]
