# Generated by Django 5.1.1 on 2024-12-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0008_alter_alumnoxhorario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnoxhorario',
            options={},
        ),
    ]
