# Generated by Django 5.1.1 on 2024-11-15 16:54

import django.db.models.deletion
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(max_length=100)),
                ('primerApellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('codigo', models.CharField(max_length=28)),
                ('fechaRegistro', models.DateField(default=usuarios.models.get_current_date)),
                ('telefono', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('actual', models.BooleanField(default=False)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('factorDeDesempeno', models.FloatField()),
                ('creditosPrimera', models.IntegerField()),
                ('creditosSegunda', models.IntegerField()),
                ('creditosTercera', models.IntegerField()),
                ('puntajeTotalPorCompetencias', models.CharField(max_length=1)),
                ('numeroSemestres', models.IntegerField()),
                ('turnoOrdenMatricula', models.IntegerField()),
                ('anioIngreso', models.DateField()),
                ('habilitado', models.BooleanField(default=True)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo', models.CharField(choices=[('Regular', 'Regular'), ('Director de Carrera', 'Director de Carrera')], max_length=30)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='AlumnoXCursosPermitidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoXcursosperm', to='cursos.curso')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnoXcursosperm', to='usuarios.alumno')),
            ],
            options={
                'unique_together': {('alumno', 'curso')},
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='cursosPermitidos',
            field=models.ManyToManyField(blank=True, related_name='alumnos_permitidos', through='usuarios.AlumnoXCursosPermitidos', to='cursos.curso'),
        ),
    ]
