# Generated by Django 5.1.1 on 2024-11-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesoParciales', models.FloatField()),
                ('pesoFinales', models.FloatField()),
                ('pesoPracticas', models.FloatField()),
                ('numPracticas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claveHorario', models.CharField(default='H000', max_length=5)),
                ('numVacantes', models.IntegerField()),
                ('numMatriculados', models.IntegerField()),
                ('numAprobados', models.IntegerField()),
                ('numDesaprobados', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('actual', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.FloatField()),
                ('nivel', models.CharField(choices=[('1', 'Uno'), ('2', 'Dos'), ('3', 'Tres'), ('4', 'Cuatro'), ('5', 'Cinco'), ('6', 'Seis'), ('7', 'Siete'), ('8', 'Ocho'), ('9', 'Nueve'), ('10', 'Diez'), ('E', 'Electivo')], max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('numHoras', models.IntegerField(blank=True)),
                ('obligatorio', models.BooleanField(default=True)),
                ('silabo', models.TextField(blank=True, null=True)),
                ('competencias', models.ManyToManyField(blank=True, related_name='cursos', to='calificacion.competencia')),
                ('formula', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='cursos.formula')),
            ],
        ),
    ]
