# Generated by Django 5.1.1 on 2024-12-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_horario_numretirados'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='cachimbos',
            field=models.BooleanField(default=False),
        ),
    ]
