# Generated by Django 5.1.1 on 2024-11-15 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calificacion', '0001_initial'),
        ('cursos', '0001_initial'),
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciaxhorario',
            name='idHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.horario'),
        ),
        migrations.AddField(
            model_name='notaalfabeticasub',
            name='idNotaAlfabetica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasAlfabeticasSub', to='calificacion.notaalfabetica'),
        ),
        migrations.AddField(
            model_name='notadisponible',
            name='idHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasDisponibles', to='cursos.horario'),
        ),
        migrations.AddField(
            model_name='notanumerica',
            name='idAlumnoXHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasNumericas', to='matricula.alumnoxhorario'),
        ),
        migrations.AddField(
            model_name='notaxcompetencia',
            name='idAlumnoXHorario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasXCompetencia', to='matricula.alumnoxhorario'),
        ),
        migrations.AddField(
            model_name='notaxcompetencia',
            name='idCompetencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calificacion.competencia'),
        ),
        migrations.AddField(
            model_name='notaalfabetica',
            name='idNotaXCompetencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notasAlfabeticas', to='calificacion.notaxcompetencia'),
        ),
        migrations.AddField(
            model_name='subcompetencia',
            name='idCompetencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcompetencias', to='calificacion.competencia'),
        ),
        migrations.AddField(
            model_name='notaalfabeticasub',
            name='idSubCompetencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotaAlfabeticaSub', to='calificacion.subcompetencia'),
        ),
        migrations.AddConstraint(
            model_name='notanumerica',
            constraint=models.UniqueConstraint(fields=('idAlumnoXHorario', 'tipoDeNota', 'indice'), name='unique_nota_constraint'),
        ),
        migrations.AddConstraint(
            model_name='notaxcompetencia',
            constraint=models.UniqueConstraint(fields=('idAlumnoXHorario', 'idCompetencia'), name='unique_nota_x_competencia_constraint'),
        ),
        migrations.AddConstraint(
            model_name='notaalfabetica',
            constraint=models.UniqueConstraint(fields=('idNotaXCompetencia', 'indice'), name='unique_nota_alfabetica_constraint'),
        ),
        migrations.AddConstraint(
            model_name='notaalfabeticasub',
            constraint=models.UniqueConstraint(fields=('idNotaAlfabetica', 'idSubCompetencia'), name='unique_nota_alfabetica_sub_constraint'),
        ),
    ]
