# Generated by Django 5.1.1 on 2024-11-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='tipo',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Director de Carrera', 'Director de Carrera'), ('Gestor de Carrera', 'Gestor de Carrera')], max_length=30),
        ),
    ]
